name: NodeJs Application CI/CD pipeline

on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v.0.3
        with:
          host: ${{ secrets.SSH_HOST}}
          hostname: root
          key: ${{secrets.SSH_KEY}}
          script: |
            cd /root/Nodejs-application-CICD-pipeline
            git pull
            docker compose up -d --build


